# Site settings
title:       Mozilla Community Space Bangalore
email:       igalaxyk@gmail.com
author:      Galaxy Kadiyala
description: "We are one of the Mozilla volunteer-run spaces around the world that help attract talent, strengthen community cohesion, become a major contribution funnels, and ultimately play a critical role in supporting Mozilla’s mission."
baseurl:     ""
url:         "http://mozillabangalore.github.io"

# Google analytics
google_analytics:

# Optional features
animated:           true
show_related_posts: false
show_post_footers:  true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: mozillabangalore

# Social icons
show_social_icons: true
github_username: MozillaBangalore
facebook_id: mozillabangalore
twitter_username: MozSpaceBLR
google_plus_id: 103287207997822666808
linkedin_username:
bitcoin_url:
paypal_url: 
flattr_button:

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     3
sass:
  compressed: true
gems:
  - jekyll-sitemap
